# Generated by Django 5.1.5 on 2025-02-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_chat_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=50)),
                ('native_language', models.CharField(max_length=50, null=True)),
                ('language_to_learn', models.CharField(max_length=50, null=True)),
                ('language_knowlege_level', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
