# Generated by Django 5.1.5 on 2025-01-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='knowlege_level',
            new_name='language_knowlege_level',
        ),
    ]
